version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: products
      - name: customers
      - name: promotions
      - name: geography
      - name: orders
      - name: order_items
      - name: payments
      - name: shipments
      - name: returns
      - name: reviews
      - name: sales
      - name: sample_submission
      - name: inventory
      - name: web_traffic
